name: Deploy to AWS S3
on:
  push:
    branches:
      - main  # O la rama donde desees activar el flujo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ AKIAQYEI5JTTBBT3NWCS }}
          aws-secret-access-key: ${{ 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 }}
          aws-region: us-west-1  # Cambia a tu región

      # 3. Sincronizar archivos con S3
      - name: Sync files to S3
        run: aws s3 sync . s3://pipeline-artifacts-2024-mama --delete

        

